services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
  
    environment:
      - POSTGRES_URL=jdbc:postgresql://db:5432/mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASS=mypassword

    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword 
    
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
