version: '3'
services:
  app:
    image: spring-petclinic
    ports:
      - "8080:8080"
  
    environment:
      - DB_URL=terraform-20241102004139871700000001.cma1xp5df2gi.us-east-1.rds.amazonaws.com
      - DB_USER=myusername
      - DB_PASSWORD=${DB_PASSWORD}


volumes:
  postgres_data:
