version: '3'
services:
  app:
    image: spring-petclinic-lite
    ports:
      - "8080:8080"
  
    environment:
      - DB_URL=terraform-20241102004139871700000001.cma1xp5df2gi.us-east-1.rds.amazonaws.com
      - DB_USER=myuser
      - DB_PASSWORD=mypassword

    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword

    volumes:
      - postgres_data:/var/lib/postgresql/data

  


volumes:
  postgres_data:
