# Use OpenJDK as base image
FROM openjdk:17-jdk-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the jar file from your host to your current location (/app) in the container
COPY ./build/libs/spring-petclinic-renamed-0.1.1*.jar /app/spring-petclinic.jar

# Copy gradle wrapper to current directory
# COPY ./gradlew /app/gradlew

# Expose PORT
EXPOSE 8083

# Command to run the application
ENTRYPOINT ["java", "-jar", "spring-petclinic.jar"]

# Command to try and run it with gradlew
# CMD ["./gradlew", "bootRun"]